# Generated by Django 3.1 on 2020-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0002_auto_20200817_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('vuelos', models.ManyToManyField(blank=True, related_name='pasajeros', to='aerolinea.Vuelo')),
            ],
        ),
    ]
